### ISSUE TITLE
Message d'erreur MaxListenersExceededWarning: Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by ThomasG77** [etalab/cadastre-mvt#1]
OS: Ubuntu 18.04 64 bits
Node version: v12.16.1 (via nvm)

J'augmente la mémoire allouée à Node avec

    export NODE_OPTIONS=--max_old_space_size=16000

Puis j'installe les dépendances et lance le script pour la France

    yarn --prod
    yarn generate-mvt

J'ai ce message d'erreur:

> (node:7612) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Keyv]. Use emitter.setMaxListeners() to increase limit
> MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [Keyv]. Use emitter.setMaxListeners() to increase limit
>     at _addListener (events.js:386:17)
>     at Keyv.addListener (events.js:402:10)
>     at new Keyv (/home/thomasg/cadastre-mvt/node_modules/cacheable-request/node_modules/keyv/src/index.js:42:20)
>     at new CacheableRequest (/home/thomasg/cadastre-mvt/node_modules/cacheable-request/src/index.js:19:16)
>     at Object.exports.preNormalizeArguments (/home/thomasg/cadastre-mvt/node_modules/got/dist/source/normalize-arguments.js:133:36)
>     at Object.exports.mergeOptions (/home/thomasg/cadastre-mvt/node_modules/got/dist/source/normalize-arguments.js:188:33)
>     at Object.exports.normalizeArguments (/home/thomasg/cadastre-mvt/node_modules/got/dist/source/normalize-arguments.js:219:27)
>     at got (/home/thomasg/cadastre-mvt/node_modules/got/dist/source/create.js:44:58)
>     at getCadastreLayerFile (/home/thomasg/cadastre-mvt/build-cadastre.js:28:26)
>     at MultiStream.streamFactory [as _queue] (/home/thomasg/cadastre-mvt/build-cadastre.js:55:26)

Il ne semble pas à priori être bloquant, le traitement continuant mais cela fait clairement douté s'il y a un problème.

**Comment by jdesboeufs** [comment]
Outdated since you removed `keyv`
